const DEFAULT_MANAGERS=["IO","Team 2","Team 3","Team 4","Team 5","Team 6","Team 7","Team 8","Team 9","Team 10"];
const SLOTS={P:2,D:8,C:8,A:6};
const TIER_LABEL={F1:"Top",F2:"Semi-top",F3:"Terza",F4:"Quarta",F5:"Scommessa"};
const CLUB_CODES=["ATA","BOL","CAG","COM","FIO","FRO","GEN","INT","JUV","LAZ","LEC","MIL","MON","NAP","PAR","ROM","SAS","TOR","UDI","VEN"];
const ALPHABET="ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
let old=localStorage.getItem("astaLiveV4")||localStorage.getItem("astaLiveV3");
let state=old?JSON.parse(old):{assignments:[],role:"D",status:"free",view:"az",managers:[...DEFAULT_MANAGERS],notes:{},sub:null};
if(!state.managers||state.managers.length!==10)state.managers=[...DEFAULT_MANAGERS];if(!state.notes)state.notes={};if(!state.assignments)state.assignments=[];if(!["az","club","score"].includes(state.view))state.view="az";if(state.sub===undefined)state.sub=null;
let selected=null;const byId=id=>PLAYERS.find(p=>p.id===id),sold=id=>state.assignments.find(a=>a.id===id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])),save=()=>localStorage.setItem("astaLiveV4",JSON.stringify(state));
function managerStats(name){const a=state.assignments.filter(x=>x.manager===name),spent=a.reduce((s,x)=>s+x.price,0);return{name,a,spent,budget:500-spent,roleCount:a.filter(x=>byId(x.id)?.r===state.role).length}}
function roleFull(name,role){return state.assignments.filter(a=>a.manager===name&&byId(a.id)?.r===role).length>=SLOTS[role]}
function renderManagerStrip(){const me=state.managers[0],others=state.managers.slice(1).map(managerStats).sort((a,b)=>b.budget-a.budget||a.name.localeCompare(b.name,"it")),ordered=[managerStats(me),...others];managerStrip.innerHTML=ordered.map((s,i)=>`<button class="managerChip ${i===0?"me":""}" data-team="${esc(s.name)}"><b>${i===0?"⭐ ":""}${esc(s.name)}</b><span>${s.budget} cr.</span><small>${state.role} ${s.roleCount}/${SLOTS[state.role]}</small></button>`).join("");[...managerStrip.querySelectorAll(".managerChip")].forEach(b=>b.onclick=()=>showSingleTeam(b.dataset.team))}
function renderSubFilters(){if(state.view==="az")subFilters.innerHTML=`<button data-sub="" class="${!state.sub?"on":""}">TUTTE</button>`+ALPHABET.map(l=>`<button class="alphaBtn ${state.sub===l?"on":""}" data-sub="${l}">${l}</button>`).join("");else if(state.view==="club")subFilters.innerHTML=`<button data-sub="" class="${!state.sub?"on":""}">TUTTE</button>`+CLUB_CODES.map(c=>`<button class="clubBtn ${state.sub===c?"on":""}" data-sub="${c}">${c}</button>`).join("");else subFilters.innerHTML="";[...subFilters.querySelectorAll("[data-sub]")].forEach(b=>b.onclick=()=>{state.sub=b.dataset.sub||null;save();render()})}
function render(){renderManagerStrip();renderSubFilters();document.querySelectorAll("[data-role]").forEach(b=>b.classList.toggle("on",b.dataset.role===state.role));document.querySelectorAll("[data-status]").forEach(b=>b.classList.toggle("on",b.dataset.status===state.status));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("on",b.dataset.view===state.view));
let arr=PLAYERS.filter(p=>p.r===state.role),term=search.value.trim().toLowerCase(),me=state.managers[0];if(state.status==="free")arr=arr.filter(p=>!sold(p.id));if(state.status==="sold")arr=arr.filter(p=>sold(p.id));if(state.status==="mine")arr=arr.filter(p=>sold(p.id)?.manager===me);if(term)arr=arr.filter(p=>p.n.toLowerCase().includes(term)||p.c.toLowerCase().includes(term)||p.tc.toLowerCase().includes(term));if(state.view==="az"&&state.sub)arr=arr.filter(p=>p.n.toUpperCase().startsWith(state.sub));if(state.view==="club"&&state.sub)arr=arr.filter(p=>p.tc===state.sub);
let groups={};if(state.view==="club"&&!state.sub){arr.sort((a,b)=>a.c.localeCompare(b.c,"it")||a.n.localeCompare(b.n,"it"));arr.forEach(p=>(groups[p.c]??=[]).push(p))}else{arr.sort(state.view==="score"?(a,b)=>b.v-a.v||a.n.localeCompare(b.n,"it"):(a,b)=>a.n.localeCompare(b.n,"it"));groups[state.view==="score"?"VALUTAZIONE ↓":state.sub||"A–Z"]=arr}
playerList.innerHTML="";if(!arr.length){playerList.innerHTML='<div class="empty">Nessun giocatore</div>';return}Object.entries(groups).forEach(([g,ps])=>{if(state.view==="club"&&!state.sub){const tot=PLAYERS.filter(p=>p.r===state.role&&p.c===g).length,free=PLAYERS.filter(p=>p.r===state.role&&p.c===g&&!sold(p.id)).length;playerList.insertAdjacentHTML("beforeend",`<div class="group">${g} · ${free} liberi / ${tot}</div>`)}else if(state.sub||state.view==="score")playerList.insertAdjacentHTML("beforeend",`<div class="group">${g}</div>`);ps.forEach(p=>{const a=sold(p.id),e=document.createElement("div");e.className="row"+(a?" sold":"");e.innerHTML=`<div class="tierBadge ${p.t}">${TIER_LABEL[p.t]||p.t}</div><div class="nm"><b>${esc(p.n)}</b><small>${p.c}${a?` · ${esc(a.manager)} ${a.price} cr.`:""}${p.r==="P"?"":` · ${esc(p.pos||"")}`}</small></div><div class="rt"><b>${p.v}%</b><small>IDEALE ${p.ideal} · MAX ${p.max}</small></div>`;e.onclick=()=>openPlayer(p);playerList.appendChild(e)})})}
function sameClubGrouped(p){const rel=state.assignments.map(a=>({a,p:byId(a.id)})).filter(x=>x.p&&x.p.r===p.r&&x.p.c===p.c),g={};rel.forEach(x=>(g[x.a.manager]??=[]).push(`${x.p.n} ${x.a.price}`));return Object.entries(g).map(([m,n])=>`<div class="assignedGroup"><b>${esc(m)}</b> → ${n.map(esc).join(" · ")}</div>`).join("")}
function openPlayer(p){selected=p;const last=p.r==="P"?`<div class="indicator"><span>🔗 Migliori accoppiamenti</span><div class="pairWrap">${(p.pair||[]).map(x=>`<span class="pair">${esc(x)}</span>`).join("")}</div></div>`:`<div class="indicator"><span>📍 Posizione</span><b>${esc(p.pos)}</b></div>`;detail.innerHTML=`<div class="hero"><div><h2>${esc(p.n)}</h2><small>${p.c} · ${p.r} · ${TIER_LABEL[p.t]||p.t}</small></div><div class="score">${p.v}%<span>VALUTAZIONE</span></div></div><div class="priceGrid"><div class="metric"><span>AFFARE ≤</span><strong>${p.aff}</strong></div><div class="metric"><span>IDEALE</span><strong>${p.ideal}</strong></div><div class="metric"><span>MAX</span><strong>${p.max}</strong></div></div><div class="indicators"><div class="indicator"><span>🔥 Potenziale bonus</span><b>${p.bonus}</b></div><div class="indicator"><span>👑 Gerarchia</span><b>${p.ger}</b></div><div class="indicator"><span>🔄 Rotazione</span><b>${p.rot}</b></div><div class="indicator"><span>🏆 Europa</span><b>${p.eu}</b></div><div class="indicator"><span>🩺 Fisico</span><b>${p.fis}</b></div><div class="indicator"><span>🟨 Disciplina</span><b>${p.disc}</b></div>${last}</div><div class="analysis"><b>ANALISI</b>${esc(p.analysis)}</div><div class="analysis"><b>${p.c} · ${p.r} GIÀ ASSEGNATI</b>${sameClubGrouped(p)||"Nessuno"}</div>`;personalNote.value=state.notes[p.id]||"";assignBtn.hidden=!!sold(p.id);assignBox.hidden=true;refreshManagers();playerDialog.showModal()}
function refreshManagers(){manager.innerHTML=state.managers.map(m=>{const full=roleFull(m,selected.r),count=state.assignments.filter(a=>a.manager===m&&byId(a.id)?.r===selected.r).length;return`<option value="${esc(m)}" ${full?"disabled":""}>${esc(m)} · ${selected.r} ${count}/${SLOTS[selected.r]}${full?" · COMPLETO":""}</option>`}).join("");const first=[...manager.options].find(o=>!o.disabled);if(first){manager.value=first.value;confirmAssign.disabled=false}else confirmAssign.disabled=true}
saveNote.onclick=()=>{if(selected){state.notes[selected.id]=personalNote.value;save();saveNote.textContent="SALVATA ✓";setTimeout(()=>saveNote.textContent="SALVA NOTA",800)}};assignBtn.onclick=()=>{assignBox.hidden=false;assignBtn.hidden=true;refreshManagers()};confirmAssign.onclick=()=>{const n=+price.value,m=manager.value;if(!n)return alert("Inserisci il prezzo.");if(!m)return alert("Nessun partecipante ha uno slot libero per questo ruolo.");if(roleFull(m,selected.r))return alert(`${m} ha già raggiunto il limite di ${SLOTS[selected.r]} per il ruolo ${selected.r}.`);if(sold(selected.id))return alert("Questo calciatore è già stato assegnato.");state.assignments.push({id:selected.id,price:n,manager:m});price.value="";save();playerDialog.close();render()};
search.oninput=()=>{const t=search.value.trim().toLowerCase();suggestions.innerHTML="";if(t.length>=2)PLAYERS.filter(p=>p.r===state.role&&!sold(p.id)&&(p.n.toLowerCase().includes(t)||p.c.toLowerCase().includes(t))).slice(0,7).forEach(p=>{const d=document.createElement("div");d.className="suggestion";d.innerHTML=`<b>${esc(p.n)}</b> · ${p.c} · ${TIER_LABEL[p.t]||p.t} · ${p.v}%`;d.onclick=()=>{search.value="";suggestions.innerHTML="";openPlayer(p)};suggestions.appendChild(d)});render()};
document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>{state.role=b.dataset.role;state.sub=null;save();render()});document.querySelectorAll("[data-status]").forEach(b=>b.onclick=()=>{state.status=b.dataset.status;save();render()});document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.sub=null;save();render()});resetBtn.onclick=()=>{state.status="free";state.view="az";state.sub=null;search.value="";suggestions.innerHTML="";save();render()};
legend.innerHTML=[["Top","Prima fascia."],["Semi-top","Seconda fascia."],["Terza","Buoni titolari/value."],["Quarta","Ultimi slot e low cost."],["Scommessa","Nuovi acquisti, primo anno in Serie A, provenienza da altre serie/campionati o emergenti con upside ma meno storico italiano."],["VALUTAZIONE %","Unico indice numerico sintetico del nostro modello."],["ROTAZIONE","MINIMA / OCCASIONALE / FREQUENTE / ALTA / IMPREVEDIBILE."],["EUROPA","Fattore che può influire sulla rotazione, ma non coincide con essa."],["AFFARE / IDEALE / MAX","Soglie operative di prezzo."]].map(x=>`<div class="legendLine"><b>${x[0]}</b><br>${x[1]}</div>`).join("");legendBtn.onclick=()=>legendDialog.showModal();
function openSettings(){managerInputs.innerHTML=state.managers.map((m,i)=>`<label class="muted">${i===0?"TU":`TEAM ${i+1}`}<input class="mgrInput" value="${esc(m)}"></label>`).join("");settingsDialog.showModal()}settingsBtn.onclick=openSettings;saveManagers.onclick=()=>{const vals=[...document.querySelectorAll(".mgrInput")].map(x=>x.value.trim()).map((x,i)=>x||DEFAULT_MANAGERS[i]),old=[...state.managers];state.assignments.forEach(a=>{const i=old.indexOf(a.manager);if(i>=0)a.manager=vals[i]});state.managers=vals;save();settingsDialog.close();render()};
function teamCard(s,rank){const by=Object.fromEntries("PDCA".split("").map(r=>[r,s.a.filter(x=>byId(x.id)?.r===r).length]));return`<div class="teamCard"><div class="teamTop"><b>${rank?rank+". ":""}${esc(s.name)}</b><b>${s.budget} cr.</b></div><small>Spesi ${s.spent} · P ${by.P}/2 · D ${by.D}/8 · C ${by.C}/8 · A ${by.A}/6</small>${s.a.length?`<small>${s.a.map(x=>`${esc(byId(x.id)?.n||"?")} ${x.price}`).join(" · ")}</small>`:""}</div>`}
function showTeams(){const sorted=state.managers.map(managerStats).sort((a,b)=>b.budget-a.budget||a.name.localeCompare(b.name,"it"));teamsContent.innerHTML=sorted.map((s,i)=>teamCard(s,i+1)).join("");teamsDialog.showModal()}function showSingleTeam(name){teamsContent.innerHTML=teamCard(managerStats(name),"");teamsDialog.showModal()}teamsBtn.onclick=showTeams;
function renderHistory(){history.innerHTML=state.assignments.length?[...state.assignments].map((a,i)=>({a,i})).reverse().map(({a,i})=>{const p=byId(a.id);return`<div class="histRow"><div><b>${esc(p?.n||"?")}</b><small>${esc(a.manager)} · ${a.price} cr. · ${p?.r||""}</small></div><button class="deleteOne" data-i="${i}">ELIMINA</button></div>`}).join(""):'<div class="empty">Nessuna assegnazione</div>';[...history.querySelectorAll(".deleteOne")].forEach(b=>b.onclick=()=>{const i=+b.dataset.i,a=state.assignments[i],p=byId(a.id);if(confirm(`Eliminare ${p?.n||"questa assegnazione"} da ${a.manager}?`)){state.assignments.splice(i,1);save();renderHistory();render()}})}auctionBtn.onclick=()=>{renderHistory();auctionDialog.showModal()};
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="asta-live-v4-backup.json";a.click();URL.revokeObjectURL(u)};importInput.onchange=async e=>{try{const obj=JSON.parse(await e.target.files[0].text());if(!obj.assignments||!obj.managers)throw 0;state=obj;state.sub=state.sub||null;save();settingsDialog.close();render();alert("Backup importato")}catch{alert("Backup non valido")}};resetAuction.onclick=()=>{if(confirm("Azzero assegnazioni e note? I nomi dei partecipanti restano.")){state.assignments=[];state.notes={};save();settingsDialog.close();render()}};
render();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");