const DEFAULT_MANAGERS=["IO","Team 2","Team 3","Team 4","Team 5","Team 6","Team 7","Team 8","Team 9","Team 10"];
const SLOTS={P:2,D:8,C:8,A:6};
const TIER_LABEL={F1:"Top",F2:"Semi-top",F3:"Terza",F4:"Quarta",F5:"Scommessa"};
const CLUB_CODES=["ATA","BOL","CAG","COM","FIO","FRO","GEN","INT","JUV","LAZ","LEC","MIL","MON","NAP","PAR","ROM","SAS","TOR","UDI","VEN","VER"];
const ALPHABET="ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
const ids=["auctionBtn","cancelAssign","managerStrip","subFilters","playerList","search","suggestions","detail","personalNote","assignBtn","assignBox","price","manager","confirmAssign","playerDialog","legend","legendBtn","legendDialog","managerInputs","settingsDialog","settingsBtn","saveManagers","teamsContent","teamsDialog","teamsBtn","history","auctionSheet","closeAuctionSheet","exportBtn","importInput","resetAuction","resetBtn","saveNote","cloudStatus","viewModeBox","syncInfo"];
const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const {auctionBtn,cancelAssign,managerStrip,subFilters,playerList,search,suggestions,detail,personalNote,assignBtn,assignBox,price,manager,confirmAssign,playerDialog,legend,legendBtn,legendDialog,managerInputs,settingsDialog,settingsBtn,saveManagers,teamsContent,teamsDialog,teamsBtn,history,auctionSheet,closeAuctionSheet,exportBtn,importInput,resetAuction,resetBtn,saveNote,cloudStatus,viewModeBox,syncInfo}=el;
function openDialog(d){if(!d)return;try{if(typeof d.showModal==="function")d.showModal();else d.setAttribute("open","")}catch(e){d.setAttribute("open","")}}
function closeDialog(d){if(!d)return;try{if(typeof d.close==="function")d.close();else d.removeAttribute("open")}catch(e){d.removeAttribute("open")}}
const DEFAULT_UI={role:"D",status:"free",view:"az",sub:null,deviceMode:"auto"};
function loadUiPrefs(){try{const x=JSON.parse(localStorage.getItem("astaLiveUiPrefsV1")||"{}");return {...DEFAULT_UI,...x}}catch{return {...DEFAULT_UI}}}
function saveUiPrefs(){localStorage.setItem("astaLiveUiPrefsV1",JSON.stringify({role:state.role,status:state.status,view:state.view,sub:state.sub,deviceMode:state.deviceMode}))}
let ui=loadUiPrefs();
let state={assignments:[],managers:[...DEFAULT_MANAGERS],notes:{},...ui};
function sharedState(){return {assignments:Array.isArray(state.assignments)?state.assignments:[],managers:Array.isArray(state.managers)&&state.managers.length===10?state.managers:[...DEFAULT_MANAGERS],notes:state.notes&&typeof state.notes==="object"?state.notes:{}}}
function normalizeShared(remote){return {assignments:Array.isArray(remote?.assignments)?remote.assignments:[],managers:Array.isArray(remote?.managers)&&remote.managers.length===10?remote.managers:[...DEFAULT_MANAGERS],notes:remote?.notes&&typeof remote.notes==="object"?remote.notes:{}}}

function applyDeviceMode(){document.body.classList.remove("device-auto","device-mobile","device-tablet","device-desktop");document.body.classList.add("device-"+(state.deviceMode||"auto"));if(viewModeBox)[...viewModeBox.querySelectorAll("[data-device]")].forEach(b=>b.classList.toggle("on",b.dataset.device===state.deviceMode))}
let selected=null;const byId=id=>PLAYERS.find(p=>p.id===id),sold=id=>state.assignments.find(a=>a.id===id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])),save=()=>{saveUiPrefs();if(window.ASTA_CLOUD?.ready)window.ASTA_CLOUD.push(sharedState())};
function managerStats(name){const a=state.assignments.filter(x=>x.manager===name),spent=a.reduce((s,x)=>s+x.price,0);return{name,a,spent,budget:500-spent,roleCount:a.filter(x=>byId(x.id)?.r===state.role).length}}
function roleFull(name,role){return state.assignments.filter(a=>a.manager===name&&byId(a.id)?.r===role).length>=SLOTS[role]}
function renderManagerStrip(){const me=state.managers[0],others=state.managers.slice(1).map(managerStats).sort((a,b)=>b.budget-a.budget||a.name.localeCompare(b.name,"it")),ordered=[managerStats(me),...others];managerStrip.innerHTML=ordered.map((s,i)=>`<button class="managerChip ${i===0?"me":""}" data-team="${esc(s.name)}"><b>${i===0?"⭐ ":""}${esc(s.name)}</b><span>${s.budget} cr.</span><small>${state.role} ${s.roleCount}/${SLOTS[state.role]}</small></button>`).join("");[...managerStrip.querySelectorAll(".managerChip")].forEach(b=>b.onclick=()=>showSingleTeam(b.dataset.team))}
function renderSubFilters(){if(state.view==="az")subFilters.innerHTML=`<button data-sub="" class="${!state.sub?"on":""}">TUTTE</button>`+ALPHABET.map(l=>`<button class="alphaBtn ${state.sub===l?"on":""}" data-sub="${l}">${l}</button>`).join("");else if(state.view==="club")subFilters.innerHTML=`<button data-sub="" class="${!state.sub?"on":""}">TUTTE</button>`+CLUB_CODES.map(c=>`<button class="clubBtn ${state.sub===c?"on":""}" data-sub="${c}">${c}</button>`).join("");else subFilters.innerHTML="";[...subFilters.querySelectorAll("[data-sub]")].forEach(b=>b.onclick=()=>{state.sub=b.dataset.sub||null;save();render()})}
function idealMid(p){const nums=String(p.ideal??"").match(/\d+/g)?.map(Number)||[];return nums.length>1?(nums[0]+nums[1])/2:(nums[0]||Math.max(1,+p.max*.75))}
function median(xs){if(!xs.length)return 1;xs=[...xs].sort((a,b)=>a-b);const m=Math.floor(xs.length/2);return xs.length%2?xs[m]:(xs[m-1]+xs[m])/2}
function livePrices(p){if(p.out)return{aff:"—",ideal:"—",max:0,n:0};const comps=state.assignments.map(a=>({a,p:byId(a.id)})).filter(x=>x.p&&!x.p.out&&x.p.r===p.r&&x.p.t===p.t&&x.p.id!==p.id&&idealMid(x.p)>0);const ratios=comps.map(x=>x.a.price/idealMid(x.p)).filter(x=>x>.15&&x<4);const raw=median(ratios);let confidence=ratios.length===0?0:ratios.length===1?.12:ratios.length===2?.30:Math.min(.85,.50+(ratios.length-3)*.06);let market=1+(raw-1)*confidence;market=Math.max(.55,Math.min(1.85,market));const me=managerStats(state.managers[0]);const ownRole=state.assignments.filter(a=>a.manager===state.managers[0]&&byId(a.id)?.r===p.r).length;const slotsLeft=Math.max(0,SLOTS[p.r]-ownRole);const freeTier=PLAYERS.filter(x=>x.r===p.r&&x.t===p.t&&!sold(x.id)).length;let personal=1;if(slotsLeft&&freeTier<=Math.max(2,slotsLeft))personal+=.06;if(me.budget<Math.max(30,slotsLeft*8))personal-=.08;personal=Math.max(.88,Math.min(1.10,personal));const m=market*personal;const aff=Math.max(1,Math.round((+p.aff||1)*m));const nums=String(p.ideal??"").match(/\d+/g)?.map(Number)||[Math.max(1,Math.round((+p.max||3)*.65))];let lo=Math.max(1,Math.round(nums[0]*m)),hi=Math.max(lo,Math.round((nums[1]??nums[0])*m));const max=Math.max(hi,Math.round((+p.max||3)*m));return{aff,ideal:lo===hi?String(lo):`${lo}–${hi}`,max,n:ratios.length}}
function render(){renderManagerStrip();renderSubFilters();document.querySelectorAll("[data-role]").forEach(b=>b.classList.toggle("on",b.dataset.role===state.role));document.querySelectorAll("[data-status]").forEach(b=>b.classList.toggle("on",b.dataset.status===state.status));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("on",b.dataset.view===state.view));
let arr=PLAYERS.filter(p=>p.r===state.role),term=search.value.trim().toLowerCase(),me=state.managers[0];if(state.status==="free")arr=arr.filter(p=>!sold(p.id));if(state.status==="sold")arr=arr.filter(p=>sold(p.id));if(state.status==="mine")arr=arr.filter(p=>sold(p.id)?.manager===me);if(term)arr=arr.filter(p=>p.n.toLowerCase().includes(term)||p.c.toLowerCase().includes(term)||p.tc.toLowerCase().includes(term));if(state.view==="az"&&state.sub)arr=arr.filter(p=>p.n.toUpperCase().startsWith(state.sub));if(state.view==="club"&&state.sub)arr=arr.filter(p=>p.tc===state.sub);
let groups={};if(state.view==="club"&&!state.sub){arr.sort((a,b)=>a.c.localeCompare(b.c,"it")||a.n.localeCompare(b.n,"it"));arr.forEach(p=>(groups[p.c]??=[]).push(p))}else{arr.sort(state.view==="score"?(a,b)=>b.v-a.v||a.n.localeCompare(b.n,"it"):(a,b)=>a.n.localeCompare(b.n,"it"));groups[state.view==="score"?"VALUTAZIONE ↓":state.sub||"A–Z"]=arr}
playerList.innerHTML="";if(!arr.length){playerList.innerHTML='<div class="empty">Nessun giocatore</div>';return}Object.entries(groups).forEach(([g,ps])=>{if(state.view==="club"&&!state.sub){const tot=PLAYERS.filter(p=>p.r===state.role&&p.c===g).length,free=PLAYERS.filter(p=>p.r===state.role&&p.c===g&&!sold(p.id)).length;playerList.insertAdjacentHTML("beforeend",`<div class="group">${g} · ${free} liberi / ${tot}</div>`)}else if(state.sub||state.view==="score")playerList.insertAdjacentHTML("beforeend",`<div class="group">${g}</div>`);ps.forEach(p=>{const a=sold(p.id),e=document.createElement("div");e.className="row"+(a?" sold":"")+(p.out?" outSerieA":"");const lp=livePrices(p);e.innerHTML=`<div class="tierBadge ${p.t}">${p.out?"FUORI A":(TIER_LABEL[p.t]||p.t)}</div><div class="nm"><b>${esc(p.n)}</b><small>${p.c}${a?` · ${esc(a.manager)} ${a.price} cr.`:""}${p.r==="P"?"":` · ${esc(p.pos||"")}`}</small></div><div class="rt"><b>${p.v}%</b><small>${p.out?"⛔ NON PIÙ IN SERIE A":`IDEALE LIVE ${lp.ideal} · MAX LIVE ${lp.max}`}</small></div>`;e.onclick=()=>openPlayer(p);playerList.appendChild(e)})})}
function sameClubGrouped(p){const rel=state.assignments.map(a=>({a,p:byId(a.id)})).filter(x=>x.p&&x.p.r===p.r&&x.p.c===p.c),g={};rel.forEach(x=>(g[x.a.manager]??=[]).push(`${x.p.n} ${x.a.price}`));return Object.entries(g).map(([m,n])=>`<div class="assignedGroup"><b>${esc(m)}</b> → ${n.map(esc).join(" · ")}</div>`).join("")}
function openPlayer(p){selected=p;const lp=livePrices(p);const pos=p.r==="P"?`<div class="pairTop"><span>🔗 Accoppiamenti</span>${(p.pair||[]).map(x=>`<b>${esc(x)}</b>`).join(" · ")}</div>`:`<div class="positionTop">📍 ${esc(p.pos||"Posizione da verificare")}</div>`;const injury=p.inj?`<div class="injuryAlert">${esc(p.inj)}</div>`:"";const out=p.out?`<div class="outSerieAlert">⛔ NON PIÙ IN SERIE A · NON ACQUISTARE</div>`:"";detail.innerHTML=`<div class="hero"><div><h2>${esc(p.n)}</h2><small>${p.c} · ${p.r} · ${TIER_LABEL[p.t]||p.t}</small>${pos}</div><div class="score">${p.v}%<span>VALUTAZIONE</span></div></div>${injury}${out}<div class="priceGrid"><div class="metric live"><span>AFFARE LIVE ≤</span><strong>${lp.aff}</strong></div><div class="metric live"><span>IDEALE LIVE</span><strong>${lp.ideal}</strong></div><div class="metric live"><span>MAX LIVE</span><strong>${lp.max}</strong></div></div><div class="indicators"><div class="indicator"><span>🔥 Bonus</span><b>${p.bonus}</b></div><div class="indicator"><span>👑 Gerarchia</span><b>${p.ger}</b></div><div class="indicator"><span>🔄 Rotazione</span><b>${p.rot}</b></div><div class="indicator"><span>🩺 Fisico</span><b>${p.fis}</b></div><div class="indicator"><span>🏆 Europa</span><b>${p.eu}</b></div><div class="indicator"><span>🟨 Disciplina</span><b>${p.disc}</b></div></div><div class="analysis"><b>ANALISI</b>${esc(p.analysis)}</div><div class="analysis compactAnalysis"><b>${p.c} · ${p.r} GIÀ ASSEGNATI</b>${sameClubGrouped(p)||"Nessuno"}</div>`;personalNote.value=state.notes[p.id]||"";assignBtn.hidden=!!sold(p.id)||!!p.out;assignBox.hidden=true;refreshManagers();openDialog(playerDialog)}
function refreshManagers(){manager.innerHTML=state.managers.map(m=>{const full=roleFull(m,selected.r),count=state.assignments.filter(a=>a.manager===m&&byId(a.id)?.r===selected.r).length;return`<option value="${esc(m)}" ${full?"disabled":""}>${esc(m)} · ${selected.r} ${count}/${SLOTS[selected.r]}${full?" · COMPLETO":""}</option>`}).join("");const first=[...manager.options].find(o=>!o.disabled);if(first){manager.value=first.value;confirmAssign.disabled=false}else confirmAssign.disabled=true}
saveNote.onclick=()=>{if(selected){state.notes[selected.id]=personalNote.value;save();saveNote.textContent="SALVATA ✓";setTimeout(()=>saveNote.textContent="SALVA NOTA",800)}};assignBtn.onclick=()=>{assignBox.hidden=false;assignBtn.hidden=true;refreshManagers()};cancelAssign.onclick=()=>{assignBox.hidden=true;assignBtn.hidden=false;price.value=""};confirmAssign.onclick=()=>{const n=+price.value,m=manager.value;if(!n)return alert("Inserisci il prezzo.");if(!m)return alert("Nessun partecipante ha uno slot libero per questo ruolo.");if(roleFull(m,selected.r))return alert(`${m} ha già raggiunto il limite di ${SLOTS[selected.r]} per il ruolo ${selected.r}.`);if(sold(selected.id))return alert("Questo calciatore è già stato assegnato.");state.assignments.push({id:selected.id,price:n,manager:m});price.value="";save();closeDialog(playerDialog);render()};
search.oninput=()=>{const t=search.value.trim().toLowerCase();suggestions.innerHTML="";if(t.length>=2)PLAYERS.filter(p=>p.r===state.role&&!sold(p.id)&&(p.n.toLowerCase().includes(t)||p.c.toLowerCase().includes(t))).slice(0,7).forEach(p=>{const d=document.createElement("div");d.className="suggestion";d.innerHTML=`<b>${esc(p.n)}</b> · ${p.c} · ${TIER_LABEL[p.t]||p.t} · ${p.v}%`;d.onclick=()=>{search.value="";suggestions.innerHTML="";openPlayer(p)};suggestions.appendChild(d)});render()};
document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>{state.role=b.dataset.role;state.sub=null;save();render()});document.querySelectorAll("[data-status]").forEach(b=>b.onclick=()=>{state.status=b.dataset.status;save();render()});document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.sub=null;save();render()});resetBtn.onclick=()=>{state.status="free";state.view="az";state.sub=null;search.value="";suggestions.innerHTML="";save();render()};
legend.innerHTML=[["Top","Prima fascia."],["Semi-top","Seconda fascia."],["Terza","Buoni titolari/value."],["Quarta","Ultimi slot e low cost."],["Scommessa","Nuovi acquisti, primo anno in Serie A, provenienza da altre serie/campionati o emergenti con upside ma meno storico italiano."],["VALUTAZIONE %","Unico indice numerico sintetico del nostro modello."],["ROTAZIONE","MINIMA / OCCASIONALE / FREQUENTE / ALTA / IMPREVEDIBILE."],["EUROPA","Fattore che può influire sulla rotazione, ma non coincide con essa."],["AFFARE / IDEALE / MAX","Soglie operative di prezzo."]].map(x=>`<div class="legendLine"><b>${x[0]}</b><br>${x[1]}</div>`).join("");legendBtn.onclick=()=>openDialog(legendDialog);
function openSettings(){applyDeviceMode();managerInputs.innerHTML=state.managers.map((m,i)=>`<label class="muted">${i===0?"TU":`TEAM ${i+1}`}<input class="mgrInput" value="${esc(m)}"></label>`).join("");openDialog(settingsDialog)}settingsBtn.onclick=openSettings;if(viewModeBox)viewModeBox.onclick=e=>{const b=e.target.closest("[data-device]");if(!b)return;state.deviceMode=b.dataset.device;applyDeviceMode();save()};saveManagers.onclick=()=>{const vals=[...document.querySelectorAll(".mgrInput")].map(x=>x.value.trim()).map((x,i)=>x||DEFAULT_MANAGERS[i]),old=[...state.managers];state.assignments.forEach(a=>{const i=old.indexOf(a.manager);if(i>=0)a.manager=vals[i]});state.managers=vals;save();closeDialog(settingsDialog);render()};
function teamCard(s,rank){const by=Object.fromEntries("PDCA".split("").map(r=>[r,s.a.filter(x=>byId(x.id)?.r===r).length]));return`<div class="teamCard"><div class="teamTop"><b>${rank?rank+". ":""}${esc(s.name)}</b><b>${s.budget} cr.</b></div><small>Spesi ${s.spent} · P ${by.P}/2 · D ${by.D}/8 · C ${by.C}/8 · A ${by.A}/6</small>${s.a.length?`<small>${s.a.map(x=>`${esc(byId(x.id)?.n||"?")} ${x.price}`).join(" · ")}</small>`:""}</div>`}
function showTeams(){const sorted=state.managers.map(managerStats).sort((a,b)=>b.budget-a.budget||a.name.localeCompare(b.name,"it"));teamsContent.innerHTML=sorted.map((s,i)=>teamCard(s,i+1)).join("");openDialog(teamsDialog)}function showSingleTeam(name){teamsContent.innerHTML=teamCard(managerStats(name),"");openDialog(teamsDialog)}teamsBtn.onclick=showTeams;
function renderHistory(){history.innerHTML=state.assignments.length?[...state.assignments].map((a,i)=>({a,i})).reverse().map(({a,i})=>{const p=byId(a.id);return`<div class="histRow"><div><b>${esc(p?.n||"?")}</b><small>${esc(a.manager)} · ${a.price} cr. · ${p?.r||""}</small></div><button class="deleteOne" data-i="${i}">ELIMINA</button></div>`}).join(""):'<div class="empty">Nessuna assegnazione</div>';[...history.querySelectorAll(".deleteOne")].forEach(b=>b.onclick=()=>{const i=+b.dataset.i,a=state.assignments[i],p=byId(a.id);if(confirm(`Eliminare ${p?.n||"questa assegnazione"} da ${a.manager}?`)){state.assignments.splice(i,1);save();renderHistory();render()}})}function openAuctionSheet(){renderHistory();auctionSheet.hidden=false;document.body.classList.add("sheetOpen");}
function closeAuctionSheetNow(){auctionSheet.hidden=true;document.body.classList.remove("sheetOpen");}
auctionBtn.onclick=e=>{e.preventDefault();e.stopPropagation();openAuctionSheet()};
closeAuctionSheet.onclick=closeAuctionSheetNow;
auctionSheet.addEventListener("click",e=>{if(e.target===auctionSheet)closeAuctionSheetNow()});
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="asta-live-v5-4-5-backup.json";a.click();URL.revokeObjectURL(u)};importInput.onchange=async e=>{try{const obj=JSON.parse(await e.target.files[0].text());if(!obj.assignments||!obj.managers)throw 0;state=obj;state.sub=state.sub||null;save();closeDialog(settingsDialog);render();alert("Backup importato")}catch{alert("Backup non valido")}};resetAuction.onclick=()=>{if(confirm("Azzero assegnazioni e note? I nomi dei partecipanti restano.")){state.assignments=[];state.notes={};save();closeDialog(settingsDialog);render()}};
window.ASTA_GET_LOCAL_STATE=()=>JSON.parse(JSON.stringify(sharedState()));if(window.ASTA_CLOUD)window.ASTA_CLOUD.getLocalState=window.ASTA_GET_LOCAL_STATE;window.addEventListener("asta-cloud-ready",()=>{if(window.ASTA_CLOUD)window.ASTA_CLOUD.getLocalState=window.ASTA_GET_LOCAL_STATE});window.addEventListener("asta-cloud-state",e=>{const remote=normalizeShared(e.detail);state={...state,...remote};saveUiPrefs();render()});applyDeviceMode();render();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");