import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getDatabase, ref, onValue, set, get } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
const firebaseConfig={apiKey:"AIzaSyClMJsr-dz1d4QS5Hn2dea5poaTWBZJqCU",authDomain:"fantacalcio-asta-live-5ccfb.firebaseapp.com",databaseURL:"https://fantacalcio-asta-live-5ccfb-default-rtdb.europe-west1.firebasedatabase.app",projectId:"fantacalcio-asta-live-5ccfb",storageBucket:"fantacalcio-asta-live-5ccfb.firebasestorage.app",messagingSenderId:"954983410799",appId:"1:954983410799:web:a3df7f79696e91e355319a"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);
let authReady=false, applying=false, stateRef=null, unsub=null, current=null;
const $=id=>document.getElementById(id), status=(txt,cls='')=>{const e=$('cloudStatus');if(e){e.textContent=txt;e.className='cloudPill '+cls}const i=$('syncInfo');if(i)i.textContent=txt};
const norm=s=>String(s||'').trim().toLocaleLowerCase('it-IT').replace(/\s+/g,' ');
async function digest(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function roomKey(name,password){return (await digest('asta-live-v1|'+norm(name)+'|'+password)).slice(0,40)}
function saved(){try{return JSON.parse(localStorage.getItem('astaLiveLeagues')||'[]')}catch{return[]}}
function remember(name,key){let a=saved().filter(x=>x.key!==key);a.unshift({name,key,last:Date.now()});localStorage.setItem('astaLiveLeagues',JSON.stringify(a.slice(0,8)));renderSaved()}
function renderSaved(){const box=$('savedLeagues');if(!box)return;const a=saved();box.innerHTML=a.length?'<b>Aste usate su questo dispositivo</b>'+a.map(x=>`<div class="savedLeague"><span>${escapeHtml(x.name)}</span><button data-key="${x.key}" data-name="${escapeHtml(x.name)}">APRI</button></div>`).join(''):'<span class="muted">Nessuna asta salvata su questo dispositivo.</span>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>connectKnown(b.dataset.name,b.dataset.key))}
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showGate(msg=''){ $('leagueGate').hidden=false;$('leagueGateMsg').textContent=msg;$('leagueBadge').hidden=true;$('leaveLeagueBtn').hidden=true; }
function hideGate(name){$('leagueGate').hidden=true;$('leagueBadge').textContent='🏆 '+name;$('leagueBadge').hidden=false;$('leaveLeagueBtn').hidden=false}
async function connectKnown(name,key){if(!authReady)return showGate('Firebase si sta collegando… riprova tra un secondo.');if(unsub){unsub();unsub=null}current={name,key};stateRef=ref(db,`rooms/${key}/state`);status('☁️ Collegamento…','warn');try{const snap=await get(stateRef);if(!snap.exists())return showGate('Asta non trovata. Inserisci nome lega e password corretti.');hideGate(name);remember(name,key);window.ASTA_CLOUD.ready=true;applying=true;window.dispatchEvent(new CustomEvent('asta-cloud-state',{detail:snap.val()}));applying=false;unsub=onValue(stateRef,s=>{if(!s.exists())return;applying=true;window.dispatchEvent(new CustomEvent('asta-cloud-state',{detail:s.val()}));setTimeout(()=>applying=false,0)});status('☁️ Sincronizzato','ok')}catch(e){console.error(e);showGate('Cloud bloccato dalle regole Firebase.');status('🔒 Cloud attende regole','warn')}}
async function enter(create){const name=$('leagueNameInput').value.trim(),pass=$('leaguePasswordInput').value;if(name.length<2||pass.length<4)return $('leagueGateMsg').textContent='Inserisci un nome lega e una password di almeno 4 caratteri.';if(!authReady)return $('leagueGateMsg').textContent='Firebase si sta collegando…';$('leagueGateMsg').textContent='Collegamento…';const key=await roomKey(name,pass),r=ref(db,`rooms/${key}/state`);try{const snap=await get(r);if(create){if(snap.exists())return $('leagueGateMsg').textContent='Esiste già un’asta con queste credenziali. Usa ENTRA.';const initial=window.ASTA_CLOUD.getLocalState?.();if(!initial)return $('leagueGateMsg').textContent='App non ancora pronta. Riprova.';await set(r,{...initial,_leagueName:name,_createdAt:Date.now(),_cloudUpdated:Date.now()})}else if(!snap.exists())return $('leagueGateMsg').textContent='Asta non trovata: controlla nome e password.';$('leaguePasswordInput').value='';await connectKnown(name,key)}catch(e){console.error(e);$('leagueGateMsg').textContent='Accesso bloccato: dobbiamo attivare le regole Firebase.';status('🔒 Cloud attende regole','warn')}}
window.ASTA_CLOUD={ready:false,getLocalState:null,push:async state=>{if(!stateRef||!window.ASTA_CLOUD.ready||applying)return;try{await set(stateRef,{...state,_leagueName:current?.name||'',_cloudUpdated:Date.now()});status('☁️ Sincronizzato','ok')}catch(e){status('⚠️ Sync fallita','err')}},openGate:()=>showGate(),current:()=>current};
$('joinLeagueBtn').onclick=()=>enter(false);$('createLeagueBtn').onclick=()=>enter(true);$('leaveLeagueBtn').onclick=()=>{window.ASTA_CLOUD.ready=false;current=null;stateRef=null;if(unsub){unsub();unsub=null}showGate()};
renderSaved();status('☁️ Autenticazione…','warn');
signInAnonymously(auth).catch(e=>{console.error(e);status('⚠️ Auth: '+((e&&e.code)||'errore').replace('auth/',''),'err');showGate('Errore autenticazione Firebase.')});
onAuthStateChanged(auth,user=>{if(!user)return;authReady=true;status('☁️ Pronto · scegli asta','warn');showGate()});
