import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getDatabase, ref, onValue, set, get } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";

const firebaseConfig={apiKey:"AIzaSyClMJsr-dz1d4QS5Hn2dea5poaTWBZJqCU",authDomain:"fantacalcio-asta-live-5ccfb.firebaseapp.com",databaseURL:"https://fantacalcio-asta-live-5ccfb-default-rtdb.europe-west1.firebasedatabase.app",projectId:"fantacalcio-asta-live-5ccfb",storageBucket:"fantacalcio-asta-live-5ccfb.firebasestorage.app",messagingSenderId:"954983410799",appId:"1:954983410799:web:a3df7f79696e91e355319a"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);
let authReady=false,applying=false,stateRef=null,roomRef=null,unsub=null,current=null;
const $=id=>document.getElementById(id);
const status=(txt,cls='')=>{const e=$('cloudStatus');if(e){e.textContent=txt;e.className='cloudPill '+cls}const i=$('syncInfo');if(i)i.textContent=txt};
const norm=s=>String(s||'').trim().toLocaleLowerCase('it-IT').replace(/\s+/g,' ');
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function digest(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function roomIdFor(name){return (await digest('asta-live-room-v2|'+norm(name))).slice(0,40)}
async function adminProof(roomId,password){return digest('asta-live-admin-v2|'+roomId+'|'+password)}
async function viewerProof(roomId,password){return digest('asta-live-view-v1|'+roomId+'|'+password)}
function saved(){try{return JSON.parse(localStorage.getItem('astaLiveLeaguesV2')||'[]')}catch{return[]}}
const SESSION_KEY='astaLiveCurrentLeagueV1';
function currentSaved(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function saveCurrent(c){localStorage.setItem(SESSION_KEY,JSON.stringify({...c,last:Date.now()}))}
function clearCurrent(){localStorage.removeItem(SESSION_KEY)}
function forget(roomId){const a=saved().filter(x=>x.roomId!==roomId);localStorage.setItem('astaLiveLeaguesV2',JSON.stringify(a));const c=currentSaved();if(c?.roomId===roomId)clearCurrent();renderSaved()}
function remember(c){let a=saved().filter(x=>x.roomId!==c.roomId);a.unshift({name:c.name,roomId:c.roomId,role:c.role||'editor',last:Date.now()});localStorage.setItem('astaLiveLeaguesV2',JSON.stringify(a.slice(0,10)));saveCurrent(c);renderSaved()}
function renderSaved(){const box=$('savedLeagues');if(!box)return;const a=saved();box.innerHTML=a.length?'<b>Aste usate su questo dispositivo</b><small class="savedHint">Le aste eliminate dal cloud vengono rimosse automaticamente. Puoi anche nasconderle solo da questo dispositivo.</small>'+a.map(x=>`<div class="savedLeague"><span>${escapeHtml(x.name)} <small>${x.role==='viewer'?'👁 spettatore':'✏️ editor'}</small></span><div class="savedLeagueActions"><button class="savedOpen" data-room="${x.roomId}" data-name="${escapeHtml(x.name)}">APRI</button><button class="savedRemove" data-remove-room="${x.roomId}" data-remove-name="${escapeHtml(x.name)}" title="Rimuovi solo da questo dispositivo">RIMUOVI</button></div></div>`).join(''):'<span class="muted">Nessuna asta salvata su questo dispositivo.</span>';box.querySelectorAll('.savedOpen').forEach(b=>b.onclick=()=>connectKnown(b.dataset.name,b.dataset.room));box.querySelectorAll('.savedRemove').forEach(b=>b.onclick=()=>{if(confirm(`Rimuovere ${b.dataset.removeName} solo da questo dispositivo? La lega resterà nel cloud.`))forget(b.dataset.removeRoom)})}
async function cleanupSavedLeagues(){if(!authReady)return;const a=saved();if(!a.length)return;let changed=false;const keep=[];for(const x of a){try{await detectAccess(x.roomId);const snap=await get(ref(db,`rooms/${x.roomId}`));if(snap.exists())keep.push(x);else changed=true}catch(e){if(String(e?.message||e).includes('not-authorized')||String(e?.code||'').includes('permission-denied'))changed=true;else keep.push(x)}}if(changed){localStorage.setItem('astaLiveLeaguesV2',JSON.stringify(keep));const c=currentSaved();if(c&&!keep.some(x=>x.roomId===c.roomId))clearCurrent();renderSaved()}}
function showGate(msg=''){ $('leagueGate').hidden=false;$('leagueGateMsg').textContent=msg;$('leagueBadge').hidden=true;$('accessBadge').hidden=true;$('leaveLeagueBtn').hidden=true; }
function hideGate(name){$('leagueGate').hidden=true;$('leagueBadge').textContent='🏆 '+name;$('leagueBadge').hidden=false;$('leaveLeagueBtn').hidden=false}
function accessLabel(c){if(!c)return'';if(c.status==='archived')return'📦 ARCHIVIATA';if(c.status==='closed')return'🔒 CHIUSA';return c.role==='viewer'?'👁 SPETTATORE':'✏️ EDITOR'}
function updateAccessUi(){const b=$('accessBadge');if(b&&current){b.textContent=accessLabel(current);b.hidden=false;b.className='accessBadge '+(current.role==='viewer'||current.status!=='active'?'readonly':'')}
 const info=$('leagueRoleInfo');if(info&&current)info.textContent=`${current.isOwner?'👑 Proprietario · ':''}${current.role==='viewer'?'Spettatore':'Editor'} · Stato: ${(current.status||'active').toUpperCase()}`;
 const oc=$('ownerLeagueControls');if(oc)oc.hidden=!current?.isOwner;
 const close=$('closeLeagueBtn'),archive=$('archiveLeagueBtn'),reopen=$('reopenLeagueBtn');if(close)close.hidden=current?.status!=='active';if(archive)archive.hidden=current?.status==='archived';if(reopen)reopen.hidden=current?.status==='active';
 window.ASTA_ACCESS={role:current?.role||'viewer',status:current?.status||'active',owner:!!current?.isOwner};window.dispatchEvent(new CustomEvent('asta-cloud-access',{detail:window.ASTA_ACCESS}));}
async function grantAccess(roomId,proof,role){const u=auth.currentUser;if(!u)throw new Error('auth-not-ready');await set(ref(db,`roomAccess/${roomId}/${u.uid}`),{role,joinedAt:Date.now(),proof})}
async function detectAccess(roomId){const u=auth.currentUser;if(!u)throw new Error('auth-not-ready');const a=await get(ref(db,`roomAccess/${roomId}/${u.uid}`));if(!a.exists())throw new Error('not-authorized');const role=a.val()?.role||'viewer';let isOwner=false;try{const s=await get(ref(db,`roomSecrets/${roomId}`));isOwner=!!s.exists()&&s.val()?.ownerUid===u.uid}catch{}return{role,isOwner}}
async function connectKnown(name,roomId,{silent=false}={}){if(!authReady)return showGate('Firebase si sta collegando… riprova tra un secondo.');if(unsub){unsub();unsub=null}status('☁️ Collegamento…','warn');try{const access=await detectAccess(roomId);roomRef=ref(db,`rooms/${roomId}`);stateRef=ref(db,`rooms/${roomId}/state`);const snap=await get(roomRef);if(!snap.exists()){forget(roomId);return showGate('Asta non trovata oppure eliminata.')}const room=snap.val(),meta=room.meta||{};current={name:meta.name||name,roomId,role:access.role,isOwner:access.isOwner,status:meta.status||'active'};hideGate(current.name);remember(current);applying=true;window.dispatchEvent(new CustomEvent('asta-cloud-state',{detail:room.state||{}}));applying=false;updateAccessUi();window.ASTA_CLOUD.ready=true;
 unsub=onValue(roomRef,s=>{if(!s.exists()){window.ASTA_CLOUD.ready=false;forget(roomId);return showGate('Questa lega è stata eliminata.')}const next=s.val(),m=next.meta||{};current={...current,name:m.name||current.name,status:m.status||'active'};applying=true;window.dispatchEvent(new CustomEvent('asta-cloud-state',{detail:next.state||{}}));setTimeout(()=>applying=false,0);updateAccessUi();status(current.status==='active'?'☁️ Sincronizzato':current.status==='closed'?'🔒 Asta chiusa':'📦 Asta archiviata',current.status==='active'?'ok':'warn')});
 status(current.status==='active'?'☁️ Sincronizzato':current.status==='closed'?'🔒 Asta chiusa':'📦 Asta archiviata',current.status==='active'?'ok':'warn')
 }catch(e){console.error(e);clearCurrent();showGate(silent?'Sessione scaduta. Apri l’asta oppure inserisci nuovamente la password.':'Per entrare inserisci nome lega e password.');status('🔐 Accesso richiesto','warn')}}
function cleanAuctionState(){return {assignments:[],managers:['IO','Team 2','Team 3','Team 4','Team 5','Team 6','Team 7','Team 8','Team 9','Team 10'],notes:{}}}
function errCode(e){return String(e?.code||e?.message||e||'errore').replace('PERMISSION_DENIED: ','').replace('auth/','')}
function gateDiag(step,msg,ok=false){const el=$('leagueGateMsg');if(!el)return;el.innerHTML=`<b>${escapeHtml(step)}</b> — ${escapeHtml(msg)}`;el.className=ok?'gateMsg ok':'gateMsg'}
async function createLeague(name,password){const roomId=await roomIdFor(name),proof=await adminProof(roomId,password),u=auth.currentUser;if(!u)throw {stage:'AUTH',code:'auth-not-ready'};const secretRef=ref(db,`roomSecrets/${roomId}`);try{await set(secretRef,{ownerUid:u.uid,adminHash:proof,createdAt:Date.now()})}catch(e){if(!String(e?.code||'').includes('permission-denied'))throw {stage:'CREAZIONE',code:errCode(e),raw:e}}try{await grantAccess(roomId,proof,'editor')}catch(e){throw {stage:'AUTORIZZAZIONE',code:errCode(e),raw:e}}const r=ref(db,`rooms/${roomId}`);let existing;try{existing=await get(r)}catch(e){throw {stage:'LETTURA',code:errCode(e),raw:e}}if(!existing.exists()){const initial=cleanAuctionState(),now=Date.now();try{await set(r,{meta:{name,status:'active',createdAt:now,updatedAt:now},state:{...initial,_leagueName:name,_createdAt:now,_cloudUpdated:now}})}catch(e){throw {stage:'STATO INIZIALE',code:errCode(e),raw:e}}}return roomId}
async function joinLeague(name,password,role='editor'){const roomId=await roomIdFor(name),proof=role==='viewer'?await viewerProof(roomId,password):await adminProof(roomId,password);try{await grantAccess(roomId,proof,role)}catch(e){throw {stage:role==='viewer'?'ACCESSO SPETTATORE':'ACCESSO EDITOR',code:errCode(e),raw:e}}return roomId}
async function enter(mode){const name=$('leagueNameInput').value.trim(),pass=$('leaguePasswordInput').value;if(name.length<3||pass.length<8)return gateDiag('DATI','Usa un nome lega di almeno 3 caratteri e una password di almeno 8 caratteri.');if(!authReady)return gateDiag('FIREBASE','Firebase si sta collegando…');try{const roomId=mode==='create'?await createLeague(name,pass):await joinLeague(name,pass,mode==='viewer'?'viewer':'editor');$('leaguePasswordInput').value='';await connectKnown(name,roomId)}catch(e){console.error('ASTA CLOUD',e.stage,e.code,e.raw||e);gateDiag(e.stage||'ERRORE',`Accesso non riuscito (${errCode(e.code||e)}). Controlla nome lega e password.`);status('⚠️ Accesso non riuscito','warn')}}
async function setLeagueStatus(next){if(!current?.isOwner)return alert('Solo il proprietario può cambiare lo stato della lega.');await set(ref(db,`rooms/${current.roomId}/meta/status`),next);await set(ref(db,`rooms/${current.roomId}/meta/updatedAt`),Date.now())}
async function setSpectatorPassword(pass){if(!current?.isOwner)return alert('Solo il proprietario può impostare la password spettatore.');if(String(pass||'').length<8)return alert('Usa almeno 8 caratteri.');const proof=await viewerProof(current.roomId,pass);await set(ref(db,`roomSecrets/${current.roomId}/viewerHash`),proof);alert('Password spettatore salvata. Ora puoi condividere nome lega + questa password in modalità SPETTATORE.')}
async function deleteLeague(){if(!current?.isOwner)return alert('Solo il proprietario può eliminare la lega.');const typed=prompt(`Per eliminare definitivamente ${current.name}, scrivi ELIMINA`);if(typed!=='ELIMINA')return;const rid=current.roomId;try{if(unsub){unsub();unsub=null}await set(ref(db,`rooms/${rid}`),null);await set(ref(db,`roomAccess/${rid}`),null);await set(ref(db,`roomSecrets/${rid}`),null);window.ASTA_CLOUD.ready=false;forget(rid);current=null;stateRef=null;roomRef=null;showGate('Lega eliminata definitivamente.');status('☁️ Pronto · scegli asta','warn')}catch(e){console.error(e);alert('Eliminazione non riuscita: '+errCode(e))}}
window.ASTA_CLOUD={ready:false,getLocalState:window.ASTA_GET_LOCAL_STATE||null,push:async state=>{if(!stateRef||!window.ASTA_CLOUD.ready||applying||current?.role!=='editor'||current?.status!=='active')return;try{const shared={assignments:Array.isArray(state?.assignments)?state.assignments:[],managers:Array.isArray(state?.managers)&&state.managers.length===10?state.managers:['IO','Team 2','Team 3','Team 4','Team 5','Team 6','Team 7','Team 8','Team 9','Team 10'],notes:state?.notes&&typeof state.notes==='object'?state.notes:{}};await set(stateRef,{...shared,_leagueName:current?.name||'',_cloudUpdated:Date.now()});await set(ref(db,`rooms/${current.roomId}/meta/updatedAt`),Date.now());status('☁️ Sincronizzato','ok')}catch(e){console.error(e);status('⚠️ Sync fallita','err')}},openGate:()=>showGate(),current:()=>current,reconnect:async()=>{const c=current||currentSaved();if(c?.name&&c?.roomId)await connectKnown(c.name,c.roomId,{silent:true})},setStatus:setLeagueStatus,setSpectatorPassword,deleteLeague};
window.dispatchEvent(new Event('asta-cloud-ready'));
$('joinLeagueBtn').onclick=()=>enter('editor');$('joinViewerBtn').onclick=()=>enter('viewer');$('createLeagueBtn').onclick=()=>enter('create');
$('leaveLeagueBtn').onclick=()=>{window.ASTA_CLOUD.ready=false;current=null;stateRef=null;roomRef=null;clearCurrent();if(unsub){unsub();unsub=null}showGate('Scegli un’altra asta oppure accedi a una nuova lega.')};
$('saveViewerPassword').onclick=()=>setSpectatorPassword($('viewerPasswordInput').value).then(()=>{$('viewerPasswordInput').value='' }).catch(e=>alert('Errore: '+errCode(e)));
$('closeLeagueBtn').onclick=()=>setLeagueStatus('closed').catch(e=>alert('Errore: '+errCode(e)));$('archiveLeagueBtn').onclick=()=>setLeagueStatus('archived').catch(e=>alert('Errore: '+errCode(e)));$('reopenLeagueBtn').onclick=()=>setLeagueStatus('active').catch(e=>alert('Errore: '+errCode(e)));$('deleteLeagueBtn').onclick=deleteLeague;
renderSaved();status('☁️ Autenticazione…','warn');
signInAnonymously(auth).catch(e=>{console.error(e);status('⚠️ Auth: '+((e&&e.code)||'errore').replace('auth/',''),'err');showGate('Errore autenticazione Firebase.')});
onAuthStateChanged(auth,async user=>{if(!user)return;authReady=true;await cleanupSavedLeagues();const c=currentSaved();if(c?.name&&c?.roomId){status('☁️ Riapro '+c.name+'…','warn');await connectKnown(c.name,c.roomId,{silent:true})}else{status('☁️ Pronto · scegli asta','warn');showGate()}});
let lastResume=0;async function resumeCurrent(){if(document.hidden||!authReady)return;const now=Date.now();if(now-lastResume<2500)return;lastResume=now;const c=current||currentSaved();if(c?.name&&c?.roomId){try{await connectKnown(c.name,c.roomId,{silent:true})}catch(e){console.error(e)}}}document.addEventListener('visibilitychange',resumeCurrent);window.addEventListener('pageshow',resumeCurrent);window.addEventListener('online',resumeCurrent);
