const LINEUPS_META={source:"SOS Fanta · Formazioni tipo Serie A 2026/27",updated:"9 settembre 2026",round:"FORMAZIONI TIPO · post-mercato e post-G3"};
const LINEUPS=[
{club:"Atalanta",code:"ATA",formation:"4-3-3",coach:"Sarri",xi:["Carnesecchi","Zappacosta","Kristensen T.","Scalvini","Bernasconi","Kessié","Gaetano","Ederson D.s.","De Ketelaere","Scamacca","Rowe"],ballots:["Zappacosta / Bellanova","Bernasconi / Kolasinac","Scamacca / Krstovic","Rowe / Raspadori"],notes:"Pasalic, Elmas e Samardzic restano alternative importanti nelle rotazioni."},
{club:"Bologna",code:"BOL",formation:"4-3-3",coach:"Tedesco",xi:["Skorupski","Zortea","Heggem","Theate","Miranda J.","Odgaard","Pobega","Ferguson","Orsolini","Dovbyk","Cambiaghi"],ballots:["Zortea / Holm","Heggem / Helland","Miranda J. / Alhassane","Odgaard / Moro N.","Dovbyk / Piccoli","Cambiaghi / Mbangula"],notes:"Bernardeschi e Odgaard sono jolly offensivi con molto spazio nelle rotazioni."},
{club:"Cagliari",code:"CAG",formation:"4-3-2-1",coach:"Pisacane",xi:["Caprile","Zè Pedro","Mina","Rodriguez Ju.","Obert","Adopo","Winks","Romano","Maldini","Fazzini","Kevin Carlos"],ballots:["Zè Pedro / Sugawara","Mina / Deiola","Kevin Carlos / Mendy P."],notes:"Nzola è un'altra alternativa forte per il ruolo di centravanti."},
{club:"Como",code:"COM",formation:"4-2-3-1",coach:"Fabregas",xi:["Butez","Couto","Ramon","Chalobah T.","Valle","Milla","Da Cunha","Diao","Paz N.","Baturina","Douvikas"],ballots:["Butez / Sanchez Ro.","Couto / Smolcic I.","Valle / Kaiki","Milla / Perrone","Da Cunha / Perrone","Diao / Rodriguez Je.","Douvikas / Kean"],notes:"Gerarchie meno rigide per gli impegni europei: previste molte rotazioni."},
{club:"Fiorentina",code:"FIO",formation:"4-1-4-1",coach:"Vanoli",xi:["De Gea","Dodò","Dragusin","Ranieri L.","Valdepenas","Fagioli","Mastantuono","Ndour","Atta","Goncalves P.","Pellegrino M."],ballots:["Ranieri L. / Viery","Valdepenas / Joao Mario","Mastantuono / Jimenez A.","Ndour / Oulai","Pellegrino M. / Beto"],notes:"Vanoli orientato sul 4-1-4-1; alcuni ruoli restano in evoluzione."},
{club:"Frosinone",code:"FRO",formation:"4-2-3-1",coach:"Alvini",xi:["Palmisani","Tchato","Calvani","Monterisi","Bracaglia","Calò","Grillitsch","Ghedjemis","Schmid","Kvernadze","Raimondo"],ballots:["Tchato / Oyono A.","Ghedjemis / Fini","Raimondo / Bobcek"],notes:"Desplanches insidia Palmisani; Terzic è alternativa a sinistra e Birligea in attacco."},
{club:"Genoa",code:"GEN",formation:"3-4-2-1",coach:"De Rossi",xi:["Bijlow","Marcandalli","Ostigard","Vasquez","Drameh","Sow","Frendrup","Mitaj","Baldanzi","El Shaarawy","Colombo"],ballots:["Drameh / Ehizibue","Sow / Meichtry","Mitaj / Ellertsson","El Shaarawy / Vitinha O."],notes:"Traoré e Meichtry sono jolly che possono entrare nelle rotazioni offensive."},
{club:"Inter",code:"INT",formation:"3-5-2",coach:"Chivu",xi:["Martinez Jo.","Akanji","Stones","Bastoni","Diouf","Barella","Calhanoglu","Jones C.","Dimarco","Martinez L.","Thuram"],ballots:["Stones / Bisseck","Diouf / Spence","Jones C. / Zielinski"],notes:"Provedel è più di una semplice riserva di Martinez; Carlos Augusto può coprire più ruoli."},
{club:"Juventus",code:"JUV",formation:"4-2-3-1",coach:"Spalletti",xi:["Vicario","Kalulu","Bremer","Lucumì","Celik","Douglas Luiz","Sarr P.","Conceicao","Mckennie","Yildiz","Kolo Muani"],ballots:["Lucumì / Kelly L.","Celik / Cambiaso","Kolo Muani / Woltemade"],notes:"Yildiz resta un riferimento della formazione tipo anche durante lo stop; Alajbegovic insidia Conceicao."},
{club:"Lazio",code:"LAZ",formation:"4-3-3",coach:"Gattuso",xi:["Mandas","Marusic","Doekhi","Provstgaard","Tavares N.","Taylor K.","Rovella","Frattesi","Isaksen","Pinamonti","Zaccagni"],ballots:["Doekhi / Sutalo J.","Rovella / Cataldi","Isaksen / Gudmundsson A."],notes:"Gudmundsson è un jolly offensivo su entrambe le fasce."},
{club:"Lecce",code:"LEC",formation:"4-3-3",coach:"Di Francesco",xi:["Falcone","Veiga D.","Tiago Gabriel","Gaspar K.","Gallo","Coulibaly L.","Ilic","Gorter","Pierotti","Geubbels","Monteiro J."],ballots:["Ilic / Ngom","Gorter / Berisha M.","Geubbels / Stulic","Monteiro J. / Fatah"],notes:"Pierotti parte avanti a destra; Gandelman e Maleh inseguono a centrocampo."},
{club:"Milan",code:"MIL",formation:"3-4-2-1",coach:"Amorim",xi:["Maignan","Gila","De Winter","Pavlovic","Chukwueze","Rabiot","Modric","Moreira","Pulisic","Cissè A.","Ramos G."],ballots:["De Winter / Gabbia","Moreira / Estupinan","Cissè A. / Saelemaekers"],notes:"Rabiot può essere utilizzato anche più avanti; Hutchinson è un'ulteriore alternativa sulla trequarti."},
{club:"Monza",code:"MON",formation:"3-4-2-1",coach:"Juric",xi:["Tornqvist","Goglichidze","Ziolkowski","Carboni A.","Tourè I.","Folorunsho","Pessina","Mangas","Colpani","Cutrone","Varela G."],ballots:["Tourè I. / Birindelli","Folorunsho / Akinsanmiro","Colpani / Ciurria","Cutrone / Mota"],notes:"Pessina resta nella formazione tipo anche durante l'infortunio; molti ballottaggi sulla trequarti."},
{club:"Napoli",code:"NAP",formation:"4-3-3",coach:"Allegri",xi:["Meret","Di Lorenzo","Rrahmani","Badiashile","Spinazzola","De Bruyne","Lobotka","Mctominay","Politano","Hojlund","Santos A."],ballots:["Badiashile / Marin R.","Politano / Vergara / Neres"],notes:"McTominay resta titolare della formazione tipo anche durante lo stop. Anguissa è la prima alternativa alle mezzali."},
{club:"Parma",code:"PAR",formation:"4-3-3",coach:"Cuesta",xi:["Corvi","Delprato","Troilo","Diego Carlos","Valeri","Bernabè","Keita M.","Fabbian","Tourè E.","Romero D.","Lontani"],ballots:["Fabbian / Ordonez C.","Romero D. / Elphege"],notes:"El Bilal Touré può giocare sia punta sia ala; Romero è in crescita nel ruolo di centravanti."},
{club:"Roma",code:"ROM",formation:"3-4-2-1",coach:"Gasperini",xi:["Svilar","Mancini","N'dicka","Hermoso","Molina N.","Cristante","Koné M.","Wesley","Dybala","Mora","Malen"],ballots:["N'dicka / Balerdi","Molina N. / Lulli","Mora / Soulè"],notes:"Dybala resta titolare se disponibile; Castro è il vice Malen e può anche affiancarlo."},
{club:"Sassuolo",code:"SAS",formation:"4-2-3-1",coach:"Aquilani",xi:["Muric","Van Der Brempt","Idzes","Leysen F.","Obrador","Matic","Bakola","Berardi","Thorstvedt","Laurientè","Esposito Se."],ballots:["Van Der Brempt / Cinquegrano","Leysen F. / Walukiewicz","Obrador / Doig","Thorstvedt / Adzic","Esposito Se. / Bowie"],notes:"Koné resta fuori per diversi mesi; quando rientrerà potrà modificare le gerarchie in mediana."},
{club:"Torino",code:"TOR",formation:"3-4-2-1",coach:"Abate",xi:["Perri","Comuzzo","Coco","Rodriguez R.","Belghali","Mandragora","Fitz-Jim","Cacciamani","Casadei","Vlasic","Simeone"],ballots:["Rodriguez R. / Comert"],notes:"Ismajli è un'altra opzione in difesa; Gineitis e Ilkhan alternative in mezzo, Zapata vice Simeone."},
{club:"Udinese",code:"UDI",formation:"3-4-2-1",coach:"Runjaic",xi:["Okoye","Palma","Kabasele","Solet","Vojvoda","Piotrowski","Karlstrom","Kamara H.","Zaniolo","Ekkelenkamp","Davis K."],ballots:["Palma / Abankwah","Kabasele / Bertola","Piotrowski / Miller L."],notes:"Zanoli tornerà a contendersi la fascia destra con Vojvoda quando recuperato."},
{club:"Venezia",code:"VEN",formation:"3-5-2",coach:"Stroppa",xi:["Stankovic F.","Schingtienne","Bella-Kotchap","Juan Jesus","Mazzocchi","Sohm","Busio","Basic","Haps","Adams A.","Yeboah J."],ballots:["Mazzocchi / Hainaut","Sohm / Perez K.","Haps / Correia T.","Adams A. / Rrahmani Al."],notes:"Rrahmani è la principale alternativa alle due punte titolari."}
];
